const data = [
    {"id": 0,
    "cover": "https://www.themoviedb.org/t/p/original/tJTgPVEYpbjFA4eSUMHP6pvanjV.jpg",
    "title": "Bojack Horseman",
    "rating": "4.5 ratings",
    "synopsis": "Conoce al caballo más querido de los 90… veinte años después. Vive en Los Ángeles donde humanos y animales antropomórficos coexisten, BoJack Horseman es la historia de un hombre (bueno, un caballo-hombre) que llegó muy rápido a la cima y ahora tiene que averiguar qué hacer.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/t7x7jnmN8F1hxS0wsnfYKOiW7Bh.jpg",
    "category": "+13",
    },

    {"id": 1,
    "cover": "https://www.themoviedb.org/t/p/original/fsQ2KHbZk12z3h3dba2ActMEudj.jpg",
    "title": "One Piece",
    "rating": "5.0 ratings",
    "synopsis": "El joven pirata Monkey D. Luffy y su variopinta tripulación emprenden un viaje épico en busca de un tesoro.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/qD211Hb5XwFxrszzBBe5EUYJerh.jpg",
    "category": "Todo publico",
    },

    {"id": 2,
    "cover": "https://www.themoviedb.org/t/p/original/4N55tgxDW0RRATyrZHbx0q9HUKv.jpg",
    "title": "Parásitos",
    "rating": "4.0 ratings",
    "synopsis": "Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    "category": "+13",
    },

    {"id": 3,
    "cover": "https://www.themoviedb.org/t/p/original/mBgynPDplmo5JTY9VfGqY35OjDu.jpg",
    "title": "Megalodón 2: La fosa",
    "rating": "3.0 ratings",
    "synopsis": "Una exploración submarina en las profundidades del océano se convierte en una espiral de caos cuando una malévola operación minera amenaza la misión y obliga al equipo de investigación a librar una arriesgada batalla por la supervivencia. Secuela de 'The Meg' (2018).",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg",
    "category": "+7",
    },

    {"id": 4,
    "cover": "https://www.themoviedb.org/t/p/original/3Sj5ubQ0BLXd6JuECq52Ira8Oor.jpg",
    "title": "Indiana Jones y el dial del destino",
    "rating": "3.5 ratings",
    "synopsis": "El arqueólogo Indiana Jones deberá emprender otra aventura contra el tiempo para intentar recuperar un dial legendario que puede cambiar el curso de la historia. Acompañado por su ahijada, Jones pronto se encuentra enfrentándose a Jürgen Voller, un ex nazi que trabaja para la NASA.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/9m161GawbY3cWxe6txd1NOHTjd0.jpg",
    "category": "+18",
    },

    {"id": 5,
    "cover": "https://www.themoviedb.org/t/p/original/zzaEJ68gtZZ6cPqffUkAl56x223.jpg",
    "title": "The Boogeyman",
    "rating": "2.0 ratings",
    "synopsis": "Todavía conmocionadas por la trágica muerte de su madre, una adolescente y su hermana menor se ven atormentadas por una presencia sádica en su casa y luchan para que su afligido padre les preste atención antes de que sea demasiado tarde.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/AvSeU3ji59QLN2tfWXzVqI6hg8x.jpg",
    "category": "+13",
    },

    {"id": 6,
    "cover": "https://www.themoviedb.org/t/p/original/7wTJxIM0xh9fgYFfwoeMjBsn2XH.jpg",
    "title": "Las tortugas ninja",
    "rating": "5.0 ratings",
    "synopsis": "Cuatro hermanos tortugas entrenados en ninjutsu por su Maestro deberán defender la ciudad de Nueva York de villanos y poderosos mutantes.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/9Iq5c65TQrr73zzPGQuiwHLfeb9.jpg",
    "category": "+3",
    },

    {"id": 7,
    "cover": "https://www.themoviedb.org/t/p/original/fNtqD4BTFj0Bgo9lyoAtmNFzxHN.jpg",
    "title": "Barbie",
    "rating": "4.0 ratings",
    "synopsis": "Barbie vive en Barbieland donde todo es ideal y lleno de música y color. Un buen día decide conocer el mundo real. Cuando el CEO de Mattel se entere, tratará de evitarlo a toda costa y devolver a Barbie a una caja.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
    "category": "+13",
    },

    {"id": 8,
    "cover": "https://www.themoviedb.org/t/p/w220_and_h330_face/aZXHjmhSSGUshLEdgsNCTH9z7Ix.jpg",
    "title": "Los asesinos de la luna",
    "rating": "3.5 ratings",
    "synopsis": "Ambientada en la Oklahoma de la década de 1920, narra los asesinatos en serie de los miembros de la nación indígena Osage, que era muy rica en petróleo; una serie de crímenes brutales que más tarde se conocería como el `Reinado del Terror`.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/toA8aVfHKPPrNDJVqnwnpQI77rr.jpg",
    "category": "+17",
    },

    {"id": 9,
    "cover": "https://www.themoviedb.org/t/p/original/mwXB7uQPke29pXIrGVz7BwEZVRR.jpg",
    "title": "El último viaje del Demeter",
    "rating": "5.0 ratings",
    "synopsis": "Basado en un solo capítulo, el Captain's Log, de la clásica novela Drácula de 1897 de Bram Stoker, la historia se desarrolla a bordo de la goleta rusa Demeter, que fue fletada para transportar carga privada (veinticuatro cajas de madera sin marcar) desde Carpatia a Londres. La película detallará los extraños eventos que acontecieron a la tripulación condenada mientras intentan sobrevivir al viaje por el océano, acechados cada noche por una aterradora presencia a bordo del barco. Cuando finalmente llegó cerca del puerto de Whitby, estaba totalmente en ruinas. No había rastro de la tripulación.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/zzFAvvLkxyd74o50IeklI8xPLvf.jpg",
    "category": "+18",
    },

    {"id": 10,
    "cover": "https://www.themoviedb.org/t/p/original/6oH378KUfCEitzJkm07r97L0RsZ.jpg",
    "title": "Elemental",
    "rating": "3.5 ratings",
    "synopsis": "En una ciudad donde los residentes del fuego, el agua, la tierra y el aire viven juntos, una joven apasionada y un chico que se deja llevar por la corriente descubrirán algo elemental: cuánto tienen en común.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/pA4sNvcohTNPx3AhEEeIu8gSt7h.jpg",
    "category": "+13",
    },

    {"id": 11,
    "cover": "https://www.themoviedb.org/t/p/original/37WcNMgNOMxdhT87MFl7tq7FM1.jpg",
    "title": "Spider-Man: Cruzando el Multiverso",
    "rating": "4.0 ratings",
    "synopsis": "Tras reencontrarse con Gwen Stacy, el amigable vecindario de Spider-Man de Brooklyn al completo es catapultado a través del Multiverso, donde se encuentra con un equipo de Spidermans encargados de proteger su propia existencia. Pero cuando los héroes se enfrentan sobre cómo manejar una nueva amenaza, Miles se encuentra enfrentado a las otras Arañas y debe redefinir lo que significa ser un héroe para poder salvar a la gente que más quiere.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/9xfDWXAUbFXQK585JvByT5pEAhe.jpg",
    "category": "+7",
    },

    {"id": 12,
    "cover": "https://www.themoviedb.org/t/p/original/fUY8FPf1zabZbiIAmpU9iBkAhR.jpg",
    "title": "Modern Family",
    "rating": "5.0 ratings",
    "synopsis": "Narrada desde la perspectiva de un documental, la serie ofrece un panorama honesto y divertido sobre la vida de varias familias, en donde se presentan la relación entre padres e hijos, diferencias generacionales y culturales.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/x4lxFIhhrDI4nWtV8osnYwbGESV.jpg",
    "category": "+13",
    },

    {"id": 13,
    "cover": "https://www.themoviedb.org/t/p/original/A7L73n5Mcxitf7Y8OYHEjNem86l.jpg",
    "title": "The Good Doctor",
    "rating": "3.0 ratings",
    "synopsis": "Un cirujano joven y autista que padece el síndrome del sabio empieza a trabajar en un hospital prestigioso. Allá tendrá que vencer el escepticismo con el que sus colegas lo reciben.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/xXRsKNJHTOGrs5wfYAxkbM2RiyT.jpg",
    "category": "+10",
    },

    {"id": 14,
    "cover": "https://www.themoviedb.org/t/p/original/md19wi4NDqi6SlNq2359LvxMwb0.jpg",
    "title": "RuPaul: Reinas del drag",
    "rating": "5.0 ratings",
    "synopsis": "La famosa drag queen RuPaul presenta este concurso con retos de lo más estilosos, mezcla de concursos de belleza y de las fantasías más divinas.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/65Sco2pAzXMHWlTrIyCVHFChfs9.jpg",
    "category": "+13",
    },

    {"id": 15,
    "cover": "https://www.themoviedb.org/t/p/original/uCM7F376UCIs5y6fMg2UyVGOmfr.jpg",
    "title": "Ley y orden",
    "rating": "3.0 ratings",
    "synopsis": "Serie sobre la investigación de crímenes en la ciudad de Nueva York. Policías y jueces son los principales protagonistas.",
    "banner": "https://www.themoviedb.org/t/p/w500_and_h282_face/oOce9hLMVFubjAJliau4kiSNPnW.jpg",
    "category": "Todo publico",
    },

]